// Angular/ZAngular_Exp/src/app/components/add-item/add-item.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { TodoServiceService } from '../../services/todo-service.service';
import { Todo } from '../../models/Todo';

@Component({
  selector: 'app-add-item',
  templateUrl: './add-item.component.html',
  styleUrl: './add-item.component.css'
})
export class AddItemComponent {


  title:string='';
  @Output() addEvent=new EventEmitter<Todo>();

  constructor(private todoService:TodoServiceService){

  }


  onSubmit(){

  const todo:Todo={title:this.title,completed:false};
  this.addEvent.emit(todo);

    
  }

}

<form class="form" (ngSubmit)="onSubmit()">

    <input type="text"  name="title" [(ngModel)]="title" placeholder="add item ..."/>
    {{title}}
    <input type="submit" value="submit"/>
</form>

// ReactJs/reactjs_1/src/components/AddItem.js
import React, { Component } from 'react'

 class AddItem extends Component{
     state={
         title:''
     }
     onChangeMethod=(e)=>{
        this.setState({[e.target.name]:e.target.value});
     }
     onSubmitForm=(e)=>{
        e.preventDefault();
        this.props.AddItem(this.state.title);
        this.setState({title:''});
     }
     render(){
        return (
            <div>
                <form onSubmit={this.onSubmitForm} className="myform">
                <input 
               
                type="text"
                name="title" 
                placeholder="add item..." 
                value={this.state.title}
                onChange={this.onChangeMethod}
                ></input>
                
                <input type="submit" value="Add Item" ></input>
                </form>
    
            </div>
        );
     }
    
}
export default AddItem;
